### ISSUE TITLE
Similar to Object Model

### ISSUE THREAD

**Issue by ryan-mahoney** [oussamahamdaoui/forgJs#24]
This seems similar to http://objectmodel.js.org/.

Can you highlight some of the differences / reasons to use this library over ObjectModel?

Thanks!

**Comment by itskolli** [comment]
We are using joi for object validation https://github.com/hapijs/joi . does this package provides same features or is there any difference?

**Comment by oussamahamdaoui** [comment]
Thank you guys for pointing these out I'm open for all suggestions.
Feel free to add new  pull requests

**Comment by gahissy** [comment]
Good job guys on sharing your work!

Can you shed some light on why you chose a constructor approach instead of functions chaining ? 
I think the latter is way less prone to errors, less verbose and benefits from IDE code completion.

```js
Rules.int().min(18).max(99)
Rules.date()
Rules.arrayOf( Rules.string() )
```
I'm using [Yup](https://github.com/jquense/yup) for validating my schemas.

**Comment by oussamahamdaoui** [comment]
hey, @gahissy thanks for pointing out this. As I said it gets really long and hard to reed for complex validation objects and i dont like nesting function calls. But i agree on the fact that with the function approch you benefit from code completion. I'd love to make both possible.

**Comment by sylvainpolletvillard** [comment]
From what I saw, forgJS intends to be a pure validation library that doesn't change the data tested, while ObjectModel uses ES6 proxies to wrap data in models and provide automatic type-checking every time you manipulate this data afterwards. I call OM a modelling library and not a validation library, because a validation library would typically not have some features like autocasting or null safe traversal.

**Comment by oussamahamdaoui** [comment]
No that’s impossible or really hard to do. It won’t be able to treat nested objects right now forgjs traverses the object recursively and stops whenever it founds an instance of ‘Rule’
