### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by oussamahamdaoui** [oussamahamdaoui/forgJs#29]
Hey every one, If you have suggestions or ideas to improuve the code please feel free to let a comment here.
Rulles:
### 1 Please use this template wich will help developers to test and better understend your request:
```javascript 
const someRule= new Rule({
    type: 'yourType',
    prop1: val1,
    prop2: val2, ...
  }, null);

  someRule.test(validValue) // returns true
  someRule.test(invalidValue) // returns false
```
### 5 If you have any questions ask them in the FAQ
# 6 Please have fun, and if you feel like not following the rulles then don't  follow them
code with love :heart:

**Comment by kwkau** [comment]
Hi, i have taken a look at forgjs and so far everything looks pretty good, but i have one request. Can we have another method from test which can check the rules specified against multiple values. Example

`const someRule= new Rule({
    type: 'yourType',
    prop1: val1,
    prop2: val2, ...
  }, null);

  someRule.testMultiple([values to test]) // returns true`

This will make validation of multiple values at once a breeze. If all the values are valid testMultiple returns true otherwise it will return the indices or the values which have failed the validation.

**Comment by kwkau** [comment]
Awesome, you are the man!!!!
